#!/usr/bin/env python

import sys
import os

PHONEBOOK_ENTRIES = "python_phonebook_entries"


def main():
    if len(sys.argv) < 2:
        exit(1)

    elif sys.argv[1] == "new":
        with open(PHONEBOOK_ENTRIES, 'a') as f:
            f.write(sys.argv[2] + " " + sys.argv[3] + "\n")
            f.close()

    elif sys.argv[1] == "list":
        if not os.path.isfile(PHONEBOOK_ENTRIES) or os.path.getsize(
                PHONEBOOK_ENTRIES) == 0:
            print("phonebook is empty")
        else:
            with open(PHONEBOOK_ENTRIES, 'r') as f:
                print(f.read())
                f.close()
    
    elif sys.argv[1] == "lookup":
        # YOUR CODE HERE #
        import re
        name = " ".join(sys.argv[2:])
        with open(PHONEBOOK_ENTRIES, 'r') as f:
            for line in f:
                if name in line:
                    print(re.search(r"[\d]{3}-[\d]{3}-[\d]{4}", line).group())
    elif sys.argv[1] == "remove":
        name = " ".join(sys.argv[2:])
        with open(PHONEBOOK_ENTRIES, 'r') as f:
            res = []
            for line in f:
                if name in line:
                    pass
                else:
                    res.append(line)
            f.close()
        with open(PHONEBOOK_ENTRIES, 'w') as f:
            for line in res:
                f.write(line)
            f.close()

    elif sys.argv[1] == "clear":
        # YOUR CODE HERE #
        os.remove(PHONEBOOK_ENTRIES)

    else:
        name = " ".join(sys.argv[1:])
        with open(PHONEBOOK_ENTRIES, 'r') as f:
            lookup = "".join(filter(lambda line: name in line, f.readlines()))
            # YOUR CODE HERE #


if __name__ == "__main__":
    main()
